# ==============================
# Hugo configuration
# ==============================

# Site info
title: Henning Giese
baseURL: "https://henninggiese.com/"

# Force the theme (works alongside Hugo Modules)
theme: ["github.com/HugoBlox/theme-academic-cv"]

# Keep outputs simple so home always renders HTML
outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]

############################
## LANGUAGE
############################
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## CONTENT & BUILD
############################
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
timeout: 600000
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$

permalinks:
  authors: "/author/:slug/"

disableAliases: true

############################
## IMAGES
############################
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture

############################
## TAXONOMIES
############################
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

############################
## MARKUP / HIGHLIGHT
############################
markup:
  highlight:
    lineNos: false

############################
## SECURITY / SITEMAP
############################
security: {}
sitemap: {}
