name: Deploy Hugo site to Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
      HUGO_MODULE_PROXY: "https://proxy.golang.org"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Go (for Hugo Modules)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Setup Hugo (extended)  # >= 0.148.2 is REQUIRED by blox-tailwind
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.0'
          extended: true

      - name: Clean module state
        run: |
          go clean -modcache
          rm -f go.mod go.sum || true
          go mod init example.com/site

      - name: Resolve Hugo Modules (use imports from config)
        run: |
          # IMPORTANT: do NOT 'hugo mod get github.com/HugoBlox/theme-academic-cv'
          # We rely on your config import: github.com/HugoBlox/hugo-blox-builder/starters/academic-cv
          hugo mod tidy
          hugo mod graph

      - name: Build
        run: hugo --minify --gc --verbose

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
